spring.application.name=demo

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=Ginasio;encrypt=true;trustServerCertificate=true
spring.datasource.username=appuser
spring.datasource.password=AppPassword123!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver